# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nate's Awesome Website
email: ngbrown11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website to display my projects and passions, moonlighting as a blog about various topics 
  ranging from sports, to TV & cinema, to technology and IoT, etc.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Mr_Innovative
github_username:  ngbrown11
linkedin_username: Nathaniel Brown

# Build settings
markdown: kramdown

# Gems
gems:
 - jemoji
 - jekyll-mentions
 - jekyll-seo-tag
